version: "3.9"

services:
  backend: 
    build: ./backend
    container_name: summarizer-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: always 
  
  frontend:
    build: ./frontend 
    container_name: summarizer-frontend
    ports:
      - "3000:80"
    restart: always 